window.SHT_CAREERS = [
  {
    "title": "3D Animator",
    "slug": "3d-animator",
    "category": "design",
    "description": "Bring characters to life for movies, games, and epic adventures!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,3d,animator",
    "resources": []
  },
  {
    "title": "Aerospace Engineer",
    "slug": "aerospace-engineer",
    "category": "engineering",
    "description": "Design rockets, build spacecraft, and launch into the future!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,aerospace,engineer",
    "resources": []
  },
  {
    "title": "AI Genomic Engineer",
    "slug": "ai-genomic-engineer",
    "category": "data",
    "description": "Sit at the cutting edge of artificial intelligence + genetics, using powerful algorithms to decode DNA, predict disease, and personalize medicine",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,ai,genomic,engineer",
    "resources": []
  },
  {
    "title": "AI Product Manager",
    "slug": "ai-product-manager",
    "category": "data",
    "description": "Lead AI products from idea to launch - balancing users, data, and impact!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,ai,product,manager",
    "resources": []
  },
  {
    "title": "AI Prompt Engineer",
    "slug": "ai-prompt-engineer",
    "category": "data",
    "description": "Write prompts that turn AI into a powerful tool for learning and creating!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,ai,prompt,engineer",
    "resources": []
  },
  {
    "title": "AI Researcher",
    "slug": "ai-researcher",
    "category": "data",
    "description": "Teach machines to think, learn, and solve real-world problems!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,ai,researcher",
    "resources": []
  },
  {
    "title": "AI Security Analyst",
    "slug": "ai-security-analyst",
    "category": "data",
    "description": "Secure AI systems and stop new kinds of digital threats!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,ai,security,analyst",
    "resources": []
  },
  {
    "title": "AI/ML Engineer",
    "slug": "ai-ml-engineer",
    "category": "data",
    "description": "Build models that learn from data and power real products!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,ai,ml,engineer",
    "resources": []
  },
  {
    "title": "Architect",
    "slug": "architect",
    "category": "design",
    "description": "Sketch bold buildings and design the spaces where people thrive!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,architect",
    "resources": []
  },
  {
    "title": "Astronaut",
    "slug": "astronaut",
    "category": "technology",
    "description": "Train for space missions and explore beyond Earth!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,astronaut",
    "resources": []
  },
  {
    "title": "Astronomer",
    "slug": "astronomer",
    "category": "science",
    "description": "Explore galaxies, study stars, and unlock the secrets of space!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,astronomer",
    "resources": []
  },
  {
    "title": "Astrophysicist",
    "slug": "astrophysicist",
    "category": "science",
    "description": "Explore the biggest mysteries of the universe\u2014from black holes and distant galaxies to the origins of space and time",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,astrophysicist",
    "resources": []
  },
  {
    "title": "Biomedical Engineer",
    "slug": "biomedical-engineer",
    "category": "engineering",
    "description": "Invent life-saving tech like prosthetics and surgical robots!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,biomedical,engineer",
    "resources": []
  },
  {
    "title": "Biotech Scientist",
    "slug": "biotech-scientist",
    "category": "science",
    "description": "Use science to cure diseases, grow food, and change the world!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,biotech,scientist",
    "resources": []
  },
  {
    "title": "Chemist",
    "slug": "chemist",
    "category": "science",
    "description": "Mix, test, and invent new materials, medicine, and makeup!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,chemist",
    "resources": []
  },
  {
    "title": "Civil Engineer",
    "slug": "civil-engineer",
    "category": "engineering",
    "description": "Design the roads, bridges, and cities of tomorrow!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,civil,engineer",
    "resources": []
  },
  {
    "title": "Climate Scientist",
    "slug": "climate-scientist",
    "category": "science",
    "description": "Use science to protect our planet and fight climate change!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,climate,scientist",
    "resources": []
  },
  {
    "title": "Customer Success Manager",
    "slug": "customer-success-manager",
    "category": "technology",
    "description": "Help customers succeed with technology and build strong relationships!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,customer,success,manager",
    "resources": []
  },
  {
    "title": "Cybersecurity Analyst",
    "slug": "cybersecurity-analyst",
    "category": "technology",
    "description": "Stop hackers, protect secrets, and be a digital hero in tech!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,cybersecurity,analyst",
    "resources": []
  },
  {
    "title": "Data Scientist",
    "slug": "data-scientist",
    "category": "data",
    "description": "Discover hidden trends in data to predict, plan, and innovate!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,data,scientist",
    "resources": []
  },
  {
    "title": "Digital Marketer",
    "slug": "digital-marketer",
    "category": "design",
    "description": "Create viral content, grow brands, and own the internet!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,digital,marketer",
    "resources": []
  },
  {
    "title": "Environmental Engineer",
    "slug": "environmental-engineer",
    "category": "engineering",
    "description": "Tackle pollution and build a cleaner, greener world!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,environmental,engineer",
    "resources": []
  },
  {
    "title": "Forensic Scientist",
    "slug": "forensic-scientist",
    "category": "science",
    "description": "Solve mysteries with science and bring truth to light!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,forensic,scientist",
    "resources": []
  },
  {
    "title": "Graphic Designer",
    "slug": "graphic-designer",
    "category": "design",
    "description": "Design logos, posters, and visuals that tell powerful stories!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,graphic,designer",
    "resources": []
  },
  {
    "title": "Health Informatics Specialist",
    "slug": "health-informatics-specialist",
    "category": "technology",
    "description": "Use data to save lives and make healthcare smarter!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,health,informatics,specialist",
    "resources": []
  },
  {
    "title": "IT Support Specialist",
    "slug": "it-support-specialist",
    "category": "technology",
    "description": "Be the tech wizard who solves problems and keeps people connected!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,it,support,specialist",
    "resources": []
  },
  {
    "title": "Marine Biologist",
    "slug": "marine-biologist",
    "category": "science",
    "description": "Dive into oceans, study sea life, and protect underwater worlds!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,marine,biologist",
    "resources": []
  },
  {
    "title": "Mechanical Engineer",
    "slug": "mechanical-engineer",
    "category": "engineering",
    "description": "Build robots, engines, and everything that moves or spins!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,mechanical,engineer",
    "resources": []
  },
  {
    "title": "Robotics Engineer",
    "slug": "robotics-engineer",
    "category": "engineering",
    "description": "Design futuristic robots that explore, build, and help humans!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,robotics,engineer",
    "resources": []
  },
  {
    "title": "Social Media Producer",
    "slug": "social-media-producer",
    "category": "design",
    "description": "Create scroll-stopping content and build online communities!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,social,media,producer",
    "resources": []
  },
  {
    "title": "Software Engineer",
    "slug": "software-engineer",
    "category": "engineering",
    "description": "Code cool apps, build tech tools, and shape the digital world!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,software,engineer",
    "resources": []
  },
  {
    "title": "Sound Engineer",
    "slug": "sound-engineer",
    "category": "engineering",
    "description": "Mix beats, fine-tune audio, and make everything sound amazing!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,sound,engineer",
    "resources": []
  },
  {
    "title": "STEM Educator",
    "slug": "stem-educator",
    "category": "technology",
    "description": "Inspire future innovators and lead STEM learning forward!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,stem,educator",
    "resources": []
  },
  {
    "title": "Sustainability Analyst",
    "slug": "sustainability-analyst",
    "category": "data",
    "description": "Use data to help organizations cut waste and protect the planet!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,sustainability,analyst",
    "resources": []
  },
  {
    "title": "Tech Choreographer",
    "slug": "tech-choreographer",
    "category": "design",
    "description": "Create high-tech dance shows that light up the stage!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,tech,choreographer",
    "resources": []
  },
  {
    "title": "Tech Entrepreneur",
    "slug": "tech-entrepreneur",
    "category": "design",
    "description": "Turn bold ideas into real-world solutions using technology",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,tech,entrepreneur",
    "resources": []
  },
  {
    "title": "UAV Pilot / Drone Operator",
    "slug": "uav-pilot-drone-operator",
    "category": "engineering",
    "description": "Fly drones for filming, mapping, and search-and-rescue missions!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,uav,pilot,drone,operator",
    "resources": []
  },
  {
    "title": "UI/UX Designer",
    "slug": "ui-ux-designer",
    "category": "design",
    "description": "Design fun, user-friendly apps people love to use every day!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,ui,ux,designer",
    "resources": []
  },
  {
    "title": "Vibe Coder",
    "slug": "vibe-coder",
    "category": "technology",
    "description": "Prototype ideas fast - mixing code and creativity to build what's next!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,vibe,coder",
    "resources": []
  },
  {
    "title": "Video Game Designer",
    "slug": "video-game-designer",
    "category": "design",
    "description": "Create epic games, design characters, and bring stories to life!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,video,game,designer",
    "resources": []
  },
  {
    "title": "Virtual Production Designer",
    "slug": "virtual-production-designer",
    "category": "design",
    "description": "Create movie magic with virtual sets and XR tech!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,virtual,production,designer",
    "resources": []
  },
  {
    "title": "Web Developer",
    "slug": "web-developer",
    "category": "technology",
    "description": "Build websites that wow the world and power online life!",
    "highSchool": [],
    "college": [],
    "career": [],
    "imageDescription": "",
    "imageQuery": "woman,web,developer",
    "resources": []
  }
];
